/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as ApiPublicPushVapidKeyRouteImport } from './routes/api.public.push-vapid-key'
import { Route as ApiPublicPushSubscriptionRouteImport } from './routes/api.public.push-subscription'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushVapidKeyRoute = ApiPublicPushVapidKeyRouteImport.update({
  id: '/api/public/push-vapid-key',
  path: '/api/public/push-vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSubscriptionRoute =
  ApiPublicPushSubscriptionRouteImport.update({
    id: '/api/public/push-subscription',
    path: '/api/public/push-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/push-subscription': typeof ApiPublicPushSubscriptionRoute
  '/api/public/push-vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/push-subscription': typeof ApiPublicPushSubscriptionRoute
  '/api/public/push-vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/push-subscription': typeof ApiPublicPushSubscriptionRoute
  '/api/public/push-vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/install'
    | '/my-orders'
    | '/privacy'
    | '/track/$token'
    | '/api/public/push-subscription'
    | '/api/public/push-vapid-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/install'
    | '/my-orders'
    | '/privacy'
    | '/track/$token'
    | '/api/public/push-subscription'
    | '/api/public/push-vapid-key'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/install'
    | '/my-orders'
    | '/privacy'
    | '/track/$token'
    | '/api/public/push-subscription'
    | '/api/public/push-vapid-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InstallRoute: typeof InstallRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  TrackTokenRoute: typeof TrackTokenRoute
  ApiPublicPushSubscriptionRoute: typeof ApiPublicPushSubscriptionRoute
  ApiPublicPushVapidKeyRoute: typeof ApiPublicPushVapidKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-vapid-key': {
      id: '/api/public/push-vapid-key'
      path: '/api/public/push-vapid-key'
      fullPath: '/api/public/push-vapid-key'
      preLoaderRoute: typeof ApiPublicPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-subscription': {
      id: '/api/public/push-subscription'
      path: '/api/public/push-subscription'
      fullPath: '/api/public/push-subscription'
      preLoaderRoute: typeof ApiPublicPushSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InstallRoute: InstallRoute,
  MyOrdersRoute: MyOrdersRoute,
  PrivacyRoute: PrivacyRoute,
  TrackTokenRoute: TrackTokenRoute,
  ApiPublicPushSubscriptionRoute: ApiPublicPushSubscriptionRoute,
  ApiPublicPushVapidKeyRoute: ApiPublicPushVapidKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
